#!/bin/bash   

if [ "$1" = "" ];   
then   
       echo "the \$1 is null"
       exit 1
fi   
  
PROCESS_NUM=`ps -ef | grep "$1" | grep -v "grep" | grep -c -v "check"`   
#PROCESS_NUM=`ps -ef | grep "$1" | grep -c -v "grep"`   
#echo $PROCESS_NUM
echo "$PROCESS_NUM"

#if [ $PROCESS_NUM -ge 1 ];   
#then   
#    echo "the $1 process is running"
#else  
#    echo "the $1 process is not running"
#fi       
  

