#!/bin/sh
./configure || exit 1
make || exit 1

mkdir -p $DESTDIR/usr/local/monkey/plugin
install plugins/check_tcp 	$DESTDIR/usr/local/monkey/plugin
install plugins/check_ssh 	$DESTDIR/usr/local/monkey/plugin
install plugins/check_udp 	$DESTDIR/usr/local/monkey/plugin
install plugins/check_http 	$DESTDIR/usr/local/monkey/plugin
install plugins/check_dns 	$DESTDIR/usr/local/monkey/plugin
install plugins/check_ping 	$DESTDIR/usr/local/monkey/plugin

