#!/bin/sh       

if  [ $# -ne 3 ]
then
    /bin/echo "$0 host plugin value"
    exit 1
else
    /bin/echo "nagios $2 $3" | /usr/bin/nc $1 43698 -w 1
fi
                                                                                                             
