#!/bin/sh
if [ $# -ne 1 ]
then
    max=80
else
    max=$1
fi
max_use=`tsar   -check| awk '{print $4}'|awk -F'=' '{print $2}' |awk -F'%' '{print $1}'|awk '{print sprintf("%d", $0);}'`
msg="OK"
if [ $max_use -ge $max ]
then
    msg="ERROR"
fi
echo $msg
