#!/bin/sh
if [ $# -ne 1 ]
then
    max=80
else
    max=$1
fi

load=`uptime |awk -F: '{print $NF}'|tr -d ' '|cut -d ',' -f 2|awk '{print sprintf("%d", $0);}'`
if [ -z "$load" ]; then
    load=0;
fi
msg="OK"
if [ $load -ge $max ]
then
    msg="ERROR"
fi
echo $msg
