#!/bin/sh
if [ $# -ne 1 ]
then
    max=80
else
    max=$1
fi
max_use=`df -h | awk 'NR>1{print substr($5,1,length($5)-1);}' | sort | tail -1`
msg="OK"
if [ $max_use -ge $max ]
then
    msg="ERROR"
fi
echo $msg
